services:
  drone:
    build: .
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./ros2_drone_ws:/root/ros2_drone_ws
      - type: bind
        source: ./../../ros2_drone_ws
        target: /root/ros2_drone_ws
    command: >
        bash -c "source /opt/ros/humble/setup.bash &&
                source /root/ros2_drone_ws/install/setup.bash &&
                MicroXRCEAgent serial --dev /dev/ttyAMA0 -b 921600 &
                ros2 run px4_ros_com offboard_control_pos &
                ros2 launch livox_ros_driver2 msg_MID360_launch.py"

    restart: unless-stopped
    stdin_open: true
    tty: true
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/ttyACM0:/dev/ttyACM0"
