output:
  storage_id: sqlite3

record:
  all: false
  topics:
    - /tf
    - /tf_static
    - /map
    - /path
    - /plan
    - /goal_pose
    - /offboard/setpoint
    - /drone_rover_distance
    - /drone/projected_map
    - /drone/projected_map_updates
    - /rover/projected_map
    - /rover/projected_map_updates
    - /global_costmap/costmap
    - /global_costmap/costmap_updates
    - /drone/octomap_binary
    - /rover/octomap_binary
  qos_profile_overrides_path: RosBag_configs/full_system_test_qos.yaml
